name: flutter_complete_project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.3+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.10.5
  # State management
  flutter_bloc: ^9.1.1
  # Code generator (mainly used with cubit & retrofit)
  freezed: ^3.2.4
  freezed_annotation: ^3.1.0
  # For dependency injection
  get_it: ^9.2.0
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.11.4
  json_annotation: ^4.9.0
  # Networking
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.9.2
  retrofit_generator: ^10.2.1
  # Localization
  intl: ^0.20.2 # Language rules & formatting
  easy_localization: ^3.0.8 # Easy translation management
  # For splash screen
  flutter_native_splash: ^2.4.7
  # An SVG rendering and widget library for Flutter, which allows painting.
  flutter_svg: ^2.2.3
  # For adapting screen and font size.
  flutter_screenutil: ^5.9.3
  firebase_core: ^4.4.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/